### ISSUE TITLE
Addition of a New Peer Reviewed Paper published by AAAI2021

### ISSUE THREAD

**Issue by marsggbo** [HzFu/COVID19_imaging_AI_paper_list#7]
our work **Automated Model Design and Benchmarking of 3D Deep Learning Models for COVID-19 Detection with Chest CT Scans** has been accepted by AAAI2021.  We would appreciate it if you could add this paper to the reading list.

Our code: https://github.com/HKBU-HPML/CovidNet3D

**Comment by HzFu** [comment]
Thanks, we have added this paper.
