### ISSUE TITLE
New paper "Bias Analysis on Public X-Ray Image Datasets of Pneumonia and COVID-19 Patients" 

### ISSUE THREAD

**Issue by issalig** [HzFu/COVID19_imaging_AI_paper_list#8]
You may consider to add the paper "Bias Analysis on Public X-Ray Image Datasets of Pneumonia and COVID-19 Patients" https://ieeexplore.ieee.org/document/9374968 where it studies the existence of bias on Xray datasets.

**Comment by HzFu** [comment]
Thanks, we have added this paper.
